# Generated by Django 3.1.1 on 2020-10-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201005_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nat_lang', models.CharField(help_text='Enter natural language(e.g. English)', max_length=20)),
            ],
        ),
    ]
