# Generated by Django 3.1.1 on 2020-10-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Lang',
        ),
    ]
