# Generated by Django 3.1.1 on 2020-10-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201007_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lang',
            new_name='Language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select a language for this book', to='catalog.Language'),
        ),
    ]
